// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkjgcknxlyyghhktumcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZramdja254bHl5Z2hoa3R1bWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTc3ODQsImV4cCI6MjA2NDQ3Mzc4NH0.ILJesXbXlJhMhU6GxER7P8X1RuDTtVAgdH4qQrwFE20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);